[server]
enableStaticServing=true

[[theme.fontFaces]]
family = "heading-font"
url = "app/static/SpaceGrotesk-Regular.ttf"
weight = 300
style = "normal"

#[[theme.fontFaces]]
#family = "body-font"
#url = "app/static/Roboto-Regular.ttf"
#weight = 300
#style = "normal"

[[theme.fontFaces]]
family = "body-font"
url = "app/static/DMSans-Regular.ttf"
weight = 300
style = "normal"

#[[theme.fontFaces]]
#family = "code-font"
#url = "app/static/Inconsolata-Regular.ttf"
#weight = 400
#style = "normal"

[[theme.fontFaces]]
family = "code-font"
url = "app/static/JetBrainsMono-VariableFont_wght.ttf"
weight = 400
style = "normal"

[theme]
#base = "dark"
primaryColor = "#2B2D30"
#backgroundColor = "#F2F2F2"
#secondaryBackgroundColor = "#00425F"
#textColor = "#efefef"
#linkColor =
#codeBackgroundColor =
font = "body-font"
codeFont = "code-font"
headingFont = "heading-font"
#fontFaces =
baseRadius = "medium"
buttonRadius = "medium"
borderColor = "lightgray"
#showWidgetBorder =
#baseFontSize = 14
#showSidebarBorder =
dataframeBorderColor = "lightgray"

[theme.sidebar]
primaryColor = "#1C1C1C"
backgroundColor = "#1E1F22"
secondaryBackgroundColor = "#00425F"
#textColor =
#linkColor =
#codeBackgroundColor =
#font =
#codeFont =
#headingFont =
#baseRadius =
#borderColor =
#showWidgetBorder =


[logger]
level = "info"
messageFormat = "%(asctime)s %(levelname) -7s %(name)s: %(message)s"

[client]
showSidebarNavigation=true
#toolbarMode = "minimal"
