[server]
enableStaticServing=true

[[theme.fontFaces]]
family = "heading-font"
url = "app/static/Roboto-Regular.ttf"
weight = 300
style = "normal"

#[[theme.fontFaces]]
#family = "body-font"
#url = "app/static/Roboto-Regular.ttf"
#weight = 300
#style = "normal"

[[theme.fontFaces]]
family = "body-font"
url = "app/static/JetBrainsMono-VariableFont_wght.ttf"
weight = 300
style = "normal"

#[[theme.fontFaces]]
#family = "code-font"
#url = "app/static/Inconsolata-Regular.ttf"
#weight = 400
#style = "normal"

[[theme.fontFaces]]
family = "code-font"
url = "app/static/JetBrainsMono-VariableFont_wght.ttf"
weight = 400
style = "normal"

[theme]
#base = "dark"
#primaryColor = "#38BDF8"
#backgroundColor = "#0F172A"
#secondaryBackgroundColor = "#00425F"
#textColor = "#efefef"
#linkColor =
#codeBackgroundColor =
font = "body-font"
codeFont = "code-font"
headingFont = "heading-font"
#fontFaces =
baseRadius = "small"
#borderColor =
#showWidgetBorder =
baseFontSize = 13
#showSidebarBorder =

[theme.sidebar]
primaryColor = "#38BDF8"
backgroundColor = "#1E293B"
secondaryBackgroundColor = "#00425F"
#textColor =
#linkColor =
#codeBackgroundColor =
#font =
#codeFont =
#headingFont =
#baseRadius =
#borderColor =
#showWidgetBorder =


[logger]
level = "info"
messageFormat = "%(asctime)s %(levelname) -7s %(name)s: %(message)s"

[client]
# showSidebarNavigation=false
# toolbarMode = "minimal"
