[server]
enableStaticServing=true

[[theme.fontFaces]]
family = "SpaceGrotesk"
url = "app/static/SpaceGrotesk-VariableFont_wght.ttf"

[[theme.fontFaces]]
family = "Roboto"
url = "app/static/Roboto-VariableFont_wdth,wght.ttf"

[[theme.fontFaces]]
family = "Work Sans"
url = "app/static/WorkSans-VariableFont_wght.ttf"

[[theme.fontFaces]]
family = "RobotoMono"
url = "app/static/RobotoMono-Bold.ttf"
style = "normal"
weight = 700

[[theme.fontFaces]]
family = "RobotoMono"
url = "app/static/RobotoMono-BoldItalic.ttf"
style = "italic"
weight = 700

[[theme.fontFaces]]
family = "RobotoMono"
url = "app/static/RobotoMono-Italic.ttf"
style = "italic"
weight = 400

[[theme.fontFaces]]
family = "RobotoMono"
url = "app/static/RobotoMono-Regular.ttf"
style = "normal"
weight = 400

[theme]
base = "dark"
primaryColor = "#0070C0"
backgroundColor = "#2a2a2a"
secondaryBackgroundColor = "black"
codeBackgroundColor = "black"
textColor = "#ffffff"
linkColor = "#0070C0"
borderColor = "#7c7c7c"
showWidgetBorder = false
baseRadius = "medium"
buttonRadius = "medium"

#showSidebarBorder = true

font = "Work Sans"
#baseFontSize = 15

codeFont = "RobotoMono"
codeFontSize = ".75rem"
#codeBackgroundColor = "#ecebe4"

headingFont = "SpaceGrotesk"
headingFontWeights = [600,500,500,500,500,500]
headingFontSizes = ["3rem", "2rem"]

[theme.sidebar]
#backgroundColor = "#121212"
backgroundColor = "black"
secondaryBackgroundColor = "#000000"
codeBackgroundColor = "#2a2a2a"
borderColor = "#0070C0"
#font = "SpaceGrotesk"
headingFontSizes = ["1.6rem", "1.4rem", "1.2rem"]



[logger]
level = "info"
messageFormat = "%(asctime)s %(levelname) -7s %(name)s: %(message)s"

[client]
showSidebarNavigation=true
toolbarMode = "minimal"
